# Generated by Django 4.1.5 on 2023-02-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
