# Generated by Django 4.1.5 on 2023-02-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_postimage_alter_author_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
    ]
